export const FEATURE_FLAGS = {
  OFFLINE_QUEUE_ENABLED: true,
  CALL_HISTORY_ENABLED: true,
  PUSH_NOTIFICATION_ENABLED: false,
  THEME_ENGINE_ENABLED: true,
  CHAT_LOCK_ENABLED: false,
  VIEW_ONCE_ENABLED: false,
  DISAPPEARING_MESSAGES_ENABLED: false,
  SCREENSHOT_PROTECTION_ENABLED: false,
  DOUBLE_RATCHET_ENABLED: false,
  LIVE_SUBTITLE_ENABLED: true,
  LOCATION_SHARING_ENABLED: false,
  FILE_ENCRYPTION_ENABLED: false,
  VOICE_NOTE_ENABLED: false,
  GROUP_CHAT_ENABLED: false,
  GROUP_CALL_ENABLED: false,
  STATUS_ENABLED: true,
  VOICE_STATUS_ENABLED: false
};
